package components

// Grand Strategy Phase G1/G2/G5/G6: interactive event engine data.
// Spec: docs/superpowers/specs/2026-08-06-grand-strategy-playable.md
//
// GameEvent is a flat, closure-free record of one pending interactive event.
// Choice EFFECTS are encoded per Kind inside systems/events.go (ResolveEvent);
// the component layer only carries the deterministic payload (DOD law).

// Event kinds generated by systems.EventDirectorSystem. The kind decides the
// popup title, body, choice labels and the effects of each choice.
const (
	EventNone            uint8 = 0
	EventTaxDemand       uint8 = 1 // City ruler demands Amount gold (ActorID = ruler)
	EventBanditShakedown uint8 = 2 // Menacing NPC demands Amount gold (ActorID = bandit)
	EventJobOffer        uint8 = 3 // City offers job Amount (ActorID = ruler, 0 = the town)
	EventInsult          uint8 = 4 // ActorID publicly insults the player
	EventFestival        uint8 = 5 // CityID holds a festival (granaries overflow)
	EventWarNews         uint8 = 6 // Player's country is now at war with country Amount
	EventPeaceNews       uint8 = 7 // Peace between player's country and country Amount
	EventRulerDied       uint8 = 8 // ActorID (former ruler of CityID) has died

	// Reserved for a later wave (marriage/intrigue) — do NOT reuse the values.
	EventMarriageProposal uint8 = 9
	EventPlotInvitation   uint8 = 10
)

// GameEvent.Flag values (kind-specific).
const (
	// EventRulerDied: the throne sits empty and the player may claim it.
	EventFlagThroneClaimable uint8 = 1
)

// GameEvent is one queued interactive event. Flat struct, 48 bytes.
type GameEvent struct {
	ID       uint64 // Unique event id (director counter; queue removal key)
	ActorID  uint64 // Identity.ID of the counterpart (ruler/bandit/insulter/employer); 0 = none
	TargetID uint64 // Secondary Identity.ID payload (kind-specific; 0 = unused)
	Tick     uint64 // Tick the event was generated on
	CityID   uint32 // City the event concerns (0 = none)
	Amount   int32  // Kind-specific payload: gold demanded, JobID offered, CountryID
	Kind     uint8  // Event* constant
	Flag     uint8  // Kind-specific flag (see EventFlag*)
	_        uint16 // Explicit padding
	_        uint32 // Explicit padding to a flat 48 bytes
}

// PendingEventsComponent queues interactive events on the possessed entity.
// Slice-bearing component precedent: AmbitionsComponent. The director caps the
// queue at systems.EventQueueCap and never duplicates a pending Kind.
type PendingEventsComponent struct {
	Events []GameEvent
}
